name = "rolldorado-bonus-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-bonus.com.pt"
HMAC_KEY = "7bd551b0b92a6f48ce36b44ff23e31d15c410e4f743abfe6dc9a26c8f7365e0a"
COOKIE_NAME = "o5u"
PLAY_PATH = "play"
BUTTON_ID = "p7ffa2304b8870e3361921d784eb89588"
GATE_SALT = "b1c457f5057fcbc9"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "fk0c"
CTA_SELECTOR = ".play-button"
